name: Documentation Update

on:
  workflow_call:
  push:
    branches:
      - develop

jobs:
  update_docs:
    if: github.actor != 'arabot-1'
    permissions: read-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ARABOT_PAT }}
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Generate Docs (Javascript)
        run: yarn run docs:client
      - name: Get short commit hash
        id: hash
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Commit updated docs
        id: commit
        run: |
          git fetch
          git pull
          git config --global user.name "Arabot-1"
          git config --global user.email "arabot-1@users.noreply.github.com"
          git add -A ./docs/
          if [ $(git diff-index HEAD ./docs | wc -l) -gt 0 ]; then
            git commit -am "Updates docs from commit $SHA_SHORT"
            git push
          fi
        env:
          SHA_SHORT: ${{ steps.hash.outputs.sha_short }}
      - name: Checkout builders-portal
        uses: actions/checkout@v3
        with:
          repository: aragon/builders-portal
          ref: staging
          path: builders-portal
          token: ${{ secrets.ARABOT_PAT }}
      - name: Copy docs (Javascript)
        run: |
          mkdir -p $GITHUB_WORKSPACE/builders-portal/docs/sdk/javascript/
          rm -rf $GITHUB_WORKSPACE/builders-portal/docs/sdk/javascript/*
          cp -R ./docs/* $GITHUB_WORKSPACE/builders-portal/docs/sdk/javascript/
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.ARABOT_PAT }}
          path: builders-portal
          commit-message: "Update sdk docs by commit ${{ steps.hash.outputs.sha_short }}"
          committer: "Arabot <arabot-1@users.noreply.github.com>"
          branch: patch/sdks-docs
          delete-branch: true
          title: Updates docs for sdk
          body: "Automated update by Github actions (Run: [${{ github.run_id }}](https://github.com/aragon/sdk/actions/runs/${{ github.run_id }}))"
          reviewers: ${{ github.actor }}
          team-reviewers: devrel