name: 01-JS-Release

on:
  pull_request:
    types:
      - closed

jobs:

  test:
    uses: ./.github/workflows/javascript_test.yml
    secrets:
      IPFS_API_KEY: ${{ secrets.IPFS_API_KEY }}

  prepare:
    name: Prepare release generation
    needs: ['test']
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    outputs:
      PACKAGE_LIST: ${{ steps.matrix.outputs.pkg_list }}
      PULL_REQUEST_LABEL_LIST: ${{ steps.matrix.outputs.pr_label_list }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: 'develop'
      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Get package-list from label-list
        id: matrix
        run: |
          PKG_LIST=$(python ./.github/scripts/generate_release_matrix.py)
          PR_LABEL_LIST="${{ github.event.pull_request.labels.*.name }}"
          echo "Pkg list: $PKG_LIST"
          echo "PR label list: $PR_LABEL_LIST"
          echo "pkg_list=$PKG_LIST" >> $GITHUB_OUTPUT
          echo "pr_label_list="$PR_LABEL_LIST" >> $GITHUB_OUTPUT"
        env:
          PULL_LABELS: ${{ toJson(github.event.pull_request.labels) }}

  release:
    name: Set Github Tag
    runs-on: ubuntu-latest
    needs: [prepare]
    #if: ${{ contains( github.event.pull_request.labels.*.name, '-release' ) }}
    if: contains(needs.prepare.outputs.PULL_REQUEST_LABEL_LIST, '-release')
    strategy:
      fail-fast: true
      matrix: ${{ fromJson(needs.prepare.outputs.PACKAGE_LIST) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: 'develop'
      - name: Get version from '${{ matrix.package }}' package.json
        id: version
        working-directory: './modules/${{ matrix.package }}'
        run: | 
          VERSION=$(cat package.json | jq -r .version)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Set Github Tag via API
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ARABOT_PAT_TRIGGER_WORKFLOW }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${{ steps.version.outputs.version }}-javascript-${{ matrix.package }}`,
              sha: "${{ github.sha }}"
            })