name: Javascript Publish
on:
  push:
    paths:
      - "javascript/**"
      - ".github/workflows/javascript_publish.yml"
    branches:
      - develop

jobs:
  checkLabels:
    runs-on: ubuntu-latest
    steps:
      - if: contains( github.event.pull_request.labels.*.name, 'fix') || contains( github.event.pull_request.labels.*.name, 'feature') || contains( github.event.pull_request.labels.*.name, 'breaking')
        run: echo "Labels are OK"
  publish:
    needs: [checkLabels]
    runs-on: ubuntu-latest
    steps:
      - name: Check labels
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        uses: ./.github/workflows/javascript_push
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: yarn install --immutable
      - name: Bump patch
        if: contains( github.event.pull_request.labels.*.name, 'fix')
        run: yarn workspaces foreach -p yarn version patch
      - name: Bump minor
        if: contains( github.event.pull_request.labels.*.name, 'feature')
        run: yarn workspaces foreach -p yarn version minor
      - name: Bump major
        if: contains( github.event.pull_request.labels.*.name, 'breaking')
        run: yarn workspaces foreach -p yarn version major
      - name: Publish
        run: yarn workspaces forach -p npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
