name: Javascript Test
on:
  workflow_call:
    inputs:
      run:
        description: "Forces a run if true"
        required: false
        type: boolean
    secrets:
      IPFS_API_KEY:
        description: "IPFS API Key"
        required: true
  push:
    branches-ignore:
      - develop
    paths:
      - 'javascript/**'
      - '.github/workflows/javascript_*'

defaults:
  run:
    working-directory: './javascript'

jobs:
  build-js:
    if: ${{ github.actor != 'arabot-1' || inputs.run }}
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['16.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
 
      - name: install deps
        run: yarn install --frozen-lockfile

      - name: Build subpackages
        run: yarn run build

      - name: Test
        run: yarn test --ci --coverage
        env:
          DAO_FACTORY: ${{ steps.contracts.outputs.dao }}
          IPFS_API_KEY: ${{ secrets.IPFS_API_KEY }}
